name: VueDatePicker-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  client:
    name: 'client tests'
    runs-on: ubuntu-latest
    container: node:12.22
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:client -- --maxWorkers=2 --verbose false --silent --color
